name: Run npm test

on: [push, pull_request]

jobs:
  build:
    name: Run tests #This is needed to find it in the branch protection settings
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
